### ISSUE TITLE
Available file formats.

### ISSUE THREAD

**Issue by techlobo** [issus/Regulator-48Vto4V-260ma#1]
Read your article with interest, as I am also looking to drive a few 3.3v control boards via a POE injector supply (ideally 48v).

Followed the link to here to have a look at the component schedule, schematc and PCB layout but unfortunately these are only available in Altium Designer format. I realise that this is a good package (and one with which you are obviously very familiar) but it is beyond the scope of the occassional hobbyist.

It would be useful therefore if the repository could also include formats that are viewable with standard utilities, or that can be imported into the free PCB utilities such as Eagle.

Many thanks for your time.

**Comment by issus** [comment]
The Altium Viewer (https://www.altium.com/viewer/) is free and web based - no account needed.

**Comment by techlobo** [comment]
Thanks for that - wasn't aware of the viewer.
